spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/company
    username: root
    password: roOt_Pw0574
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    username: 2398941475@qq.com
    password: yukgfkagkkkndhgi
    host: smtp.qq.com
  mvc:
    view:
      prefix: classpath:/static/
      suffix: .html
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  address: 0.0.0.0
  port: 8081
